#define LOAD(addr)                      tm_load32(tx, (tm_word32 *)addr)
//#define LOADD(addr)			tm_load_double(tx, (double *)addr)
#define LOADD(addr)			(double)tm_load64(tx, (tm_word64 *)addr)
#define LOAD64(addr)			tm_load64(tx, (tm_word64 *)addr)
#define STORE(addr, value)              tm_store32(tx, (tm_word32 *)addr, (tm_word32)value)
//#define STORED(addr, value)		tm_store_double(tx, (double *)addr, value)
#define STORED(addr, value)		tm_store64(tx, (tm_word64 *)addr, (tm_word64)value)
#define STORE32(addr, value)		tm_store32(tx, (int *)addr, (int)value)
#define STORE64(addr, value)		tm_store64(tx, (tm_word64 *)addr, (tm_word64)value)
